const CHAR = "CHAR";
const VARCHAR = "VARCHAR";
const BINARY = "BINARY";
const VARBINARY = "VARBINARY";
const TINYBLOB = "TINYBLOB";
const TINYTEXT = "TINYTEXT";
const TEXT = "TEXT";
const BLOB = "BLOB";
const MEDIUMTEXT = "MEDIUMTEXT";
const MEDIUMBLOB = "MEDIUMBLOB";
const LONGTEXT = "LONGTEXT";
const LONGBLOB = "LONGBLOB";
const ENUM = "ENUM";
const SET = "SET";

const BIT = "BIT";
const TINYINT = "TINYINT";
const BOOL = "BOOL";
const BOOLEAN = "BOOLEAN";
const SMALLINT = "SMALLINT";
const MEDIUMINT = "MEDIUMINT";
const INT = "INT";
const INTEGER = "INTEGER";
const BIGINT = "BIGINT";
const FLOAT = "FLOAT";
const DOUBLE = "DOUBLE";
const DOUBLE_PRECISION = "DOUBLE PRECISION";
const DECIMAL = "DECIMAL";
const DEC = "DEC";

const DATE = "DATE";
const DATETIME = "DATETIME";
const TIMESTAMP = "TIMESTAMP";
const TIME = "TIME";
const YEAR = "YEAR";

export {
  CHAR,
  VARCHAR,
  BINARY,
  VARBINARY,
  TINYBLOB,
  TINYTEXT,
  TEXT,
  BLOB,
  MEDIUMTEXT,
  MEDIUMBLOB,
  LONGTEXT,
  LONGBLOB,
  ENUM,
  SET,
  BIT,
  TINYINT,
  BOOL,
  BOOLEAN,
  SMALLINT,
  MEDIUMINT,
  INT,
  INTEGER,
  BIGINT,
  FLOAT,
  DOUBLE,
  DOUBLE_PRECISION,
  DECIMAL,
  DEC,
  DATE,
  DATETIME,
  TIMESTAMP,
  TIME,
  YEAR,
};
