version: "3"
services:
  web:
    image: node   #node镜像名称
    working_dir: /code      #工作目录
    volumes:                #挂载点
      - .:/code       #把本地当前目录挂载到容器的/code目录
    ports:                  #端口映射
      - "39002:39002"   #本地端口：容器端口
    command: npm run start      #这条命令会在工作目录下执行
  mysql:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql     #挂载当前的data目录到容器默认mysql存储目录
    environment: #环境变量
      - MYSQL_ROOT_PASSWORD=123456    #mysql的root密码
      - MYSQL_DATABASE=test_db     #mysql的初始化数据库
    ports:
      - "3306:3306"
  nginx:
    image: nginx
    volumes:
      - ./static:/code/static
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf    #挂在nginx服务的配置文件到容器里
    ports:
      - "80:80"