CREATE TABLE IF NOT EXISTS billTags (
     id INT(11) NOT NULL AUTO_INCREMENT,
     billId INT(11),
     tagId INT(11),
     createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;