CREATE TABLE IF NOT EXISTS userReports (
    id INT(11) NOT NULL AUTO_INCREMENT,
    userId INT(11),
    reportDate DATE,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;